import { Lead, ChatMessage, DocumentReq } from '@/types'

const yesterday = new Date(Date.now() - 86400000).toISOString()
const tomorrow = new Date(Date.now() + 86400000).toISOString()

export const MOCK_LEADS: Lead[] = [
  {
    id: 'l1',
    name: 'Maria das Graças Silva',
    phone: '(11) 98765-4321',
    pipelineId: 'p1',
    stage: 'NOVO LEAD',
    heat: 'Morno',
    tags: ['Aposentadoria Rural'],
    timeInStage: '2h',
    unread: true,
    benefitType: 'Aposentadoria por Idade',
    city: 'São Paulo, SP',
    assignee: 'SDR João',
    aiScore: 85,
    tasks: [
      {
        id: 't1',
        title: 'Ligar para confirmar dados',
        description: 'Verificar se trabalhou em regime de economia familiar.',
        completed: false,
        createdAt: new Date().toISOString(),
        dueDate: yesterday,
      },
    ],
  },
  {
    id: 'l2',
    name: 'Antônio Ferreira',
    phone: '(31) 99123-4567',
    pipelineId: 'p1',
    stage: 'EM QUALIFICAÇÃO',
    heat: 'Quente',
    tags: ['Segurado Qualificado'],
    timeInStage: '1d',
    unread: false,
    benefitType: 'BPC/LOAS',
    city: 'Belo Horizonte, MG',
    assignee: 'SDR João',
    aiScore: 92,
    tasks: [
      {
        id: 't2',
        title: 'Enviar formulário de saúde',
        description: '',
        completed: false,
        createdAt: new Date().toISOString(),
        dueDate: tomorrow,
      },
      {
        id: 't3',
        title: 'Verificar restrições de renda',
        description: '',
        completed: true,
        createdAt: new Date().toISOString(),
        dueDate: yesterday,
      },
    ],
  },
  {
    id: 'l3',
    name: 'José Carlos Oliveira',
    phone: '(41) 98888-7777',
    pipelineId: 'p1',
    stage: 'AGUARDANDO DOCUMENTOS',
    heat: 'Quente',
    tags: ['Falta CNIS', 'Aguardando Doc'],
    timeInStage: '3d',
    unread: false,
    benefitType: 'Aposentadoria por Tempo',
    city: 'Curitiba, PR',
    assignee: 'SDR Ana',
    aiScore: 88,
  },
  {
    id: 'l4',
    name: 'Lucia Fernandes',
    phone: '(21) 97777-6655',
    pipelineId: 'p1',
    stage: 'ANÁLISE JURÍDICA',
    heat: 'Morno',
    tags: ['Documentos OK'],
    timeInStage: '4h',
    unread: false,
    benefitType: 'Auxílio Doença',
    city: 'Rio de Janeiro, RJ',
    assignee: 'Dr. Roberto',
    aiScore: 75,
  },
  {
    id: 'l5',
    name: 'Carlos Mendes',
    phone: '(85) 99999-1111',
    pipelineId: 'p1',
    stage: 'CONTRATO ENVIADO',
    heat: 'Quente',
    tags: ['Urgente'],
    timeInStage: '2d',
    unread: true,
    benefitType: 'Aposentadoria Especial',
    city: 'Fortaleza, CE',
    assignee: 'Closer Paula',
    aiScore: 95,
    activeFlows: [{ flowId: 'f1', currentStepOrder: 1 }],
    tasks: [
      {
        id: 't_f1_1',
        title: 'Follow-up: Contato Urgente (Etapa 1)',
        description:
          '[Gerado por IA]: Crie uma mensagem urgente para agendar reunião de fechamento hoje.',
        completed: false,
        createdAt: new Date().toISOString(),
        dueDate: new Date().toISOString(),
        flowId: 'f1',
        stepOrder: 1,
      },
    ],
  },
]

export const MOCK_DOCS: DocumentReq[] = [
  { id: 'd1', name: 'RG / CPF', status: 'ok' },
  { id: 'd2', name: 'Comprovante de Residência', status: 'ok' },
  { id: 'd3', name: 'Extrato CNIS', status: 'pending' },
  { id: 'd4', name: 'CTPS', status: 'rejected' },
]

export const MOCK_CHAT: ChatMessage[] = [
  {
    id: 'c1',
    leadId: 'l1',
    sender: 'ai',
    text: 'Olá Maria! Sou a assistente virtual do escritório. Vi que você tem interesse em Aposentadoria.',
    timestamp: '10:00',
  },
  {
    id: 'c2',
    leadId: 'l1',
    sender: 'lead',
    text: 'Sim, eu trabalhei na roça muitos anos.',
    timestamp: '10:05',
  },
  {
    id: 'c3',
    leadId: 'l1',
    sender: 'ai',
    text: 'Entendi. Você tem documentos que comprovem esse período (como bloco de notas, certidão de casamento)?',
    timestamp: '10:06',
  },
  {
    id: 'c4',
    leadId: 'l1',
    sender: 'sdr',
    text: 'Vou assumir o atendimento por aqui. Olá Maria, tudo bem?',
    timestamp: '10:15',
  },
]
